language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

matrix:
  fast_finish: true
  exclude:
    - php: nightly
      env: REMOVE_XDEBUG="1"

env:
  - REMOVE_XDEBUG="0"
  - REMOVE_XDEBUG="1"

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - if [ "$REMOVE_XDEBUG" = "1" ]; then phpenv config-rm xdebug.ini; fi

install: travis_retry composer install --no-interaction

script:
  - composer tests

jobs:
  include:
    - stage: Test
      php: 5.6
      env: 
        COMPOSER_OPTIONS: "--prefer-lowest"
        REMOVE_XDEBUG: "1"
      install: travis_retry composer install --no-interaction --prefer-lowest
    - stage: Code style
      php: 7.2
      env: 
        CS-FIXER: true
        REMOVE_XDEBUG: "1"
      script: 
        - composer phpcs
    - stage: Coverage
      script:
        - phpdbg -qrr vendor/bin/phpunit --verbose --configuration phpunit.xml.dist --coverage-clover tests/clover.xml
      after_success:
        - wget https://scrutinizer-ci.com/ocular.phar
        - php ocular.phar code-coverage:upload --format=php-clover tests/clover.xml --revision=$TRAVIS_COMMIT
