language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly

matrix:
  allow_failures:
    - php: hhvm-3.12
    - php: nightly
  fast_finish: true
  include:
    - php: hhvm-3.12
      env: REMOVE_XDEBUG="0" HHVM="1"
      dist: trusty
  exclude:
    - php: nightly
      env: REMOVE_XDEBUG="1"

env:
  - REMOVE_XDEBUG="0"
  - REMOVE_XDEBUG="1"

sudo: required

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - sudo apt-get install --yes net-tools
  - if [ "$REMOVE_XDEBUG" = "1" ]; then phpenv config-rm xdebug.ini; fi
  - composer self-update

install: travis_retry composer install --no-interaction

script:
  - composer phpcs
  - composer tests-travis

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - if [ $(phpenv version-name) = "5.5" ] && [ "$REMOVE_XDEBUG" = "0" ]; then php ocular.phar code-coverage:upload --format=php-clover tests/clover.xml --revision=$TRAVIS_COMMIT; fi
  - if [ $(phpenv version-name) = "5.6" ] && [ "$REMOVE_XDEBUG" = "0" ]; then php ocular.phar code-coverage:upload --format=php-clover tests/clover.xml --revision=$TRAVIS_COMMIT; fi
  - if [ $(phpenv version-name) = "7.0" ] && [ "$REMOVE_XDEBUG" = "0" ]; then php ocular.phar code-coverage:upload --format=php-clover tests/clover.xml --revision=$TRAVIS_COMMIT; fi
  - if [ $(phpenv version-name) = "7.1" ] && [ "$REMOVE_XDEBUG" = "0" ]; then php ocular.phar code-coverage:upload --format=php-clover tests/clover.xml --revision=$TRAVIS_COMMIT; fi
