language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

matrix:
  fast_finish: true
  exclude:
    - php: nightly
      env: REMOVE_XDEBUG="1"

env:
  - REMOVE_XDEBUG="0"
  - REMOVE_XDEBUG="1"

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - if [ "$REMOVE_XDEBUG" = "1" ]; then phpenv config-rm xdebug.ini; fi
  - composer self-update

install: travis_retry composer install --no-interaction

script:
  - composer phpcs
  - composer tests-travis

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - if [ $(phpenv version-name) = "5.6" ] && [ "$REMOVE_XDEBUG" = "0" ]; then php ocular.phar code-coverage:upload --format=php-clover tests/clover.xml --revision=$TRAVIS_COMMIT; fi
  - if [ $(phpenv version-name) = "7.0" ] && [ "$REMOVE_XDEBUG" = "0" ]; then php ocular.phar code-coverage:upload --format=php-clover tests/clover.xml --revision=$TRAVIS_COMMIT; fi
  - if [ $(phpenv version-name) = "7.1" ] && [ "$REMOVE_XDEBUG" = "0" ]; then php ocular.phar code-coverage:upload --format=php-clover tests/clover.xml --revision=$TRAVIS_COMMIT; fi
  - if [ $(phpenv version-name) = "7.2" ] && [ "$REMOVE_XDEBUG" = "0" ]; then php ocular.phar code-coverage:upload --format=php-clover tests/clover.xml --revision=$TRAVIS_COMMIT; fi
