language: php

php:
    - 7.2
    - 7.3
    - 7.4
    - nightly

env:
    - dependencies=highest
    - dependencies=lowest

cache:
    directories:
        - $HOME/.composer/cache

stages:
    - Code style & static analysis
    - Test

jobs:
    fast_finish: true
    include:
        - &code-style-static-analysis
          stage: Code style & static analysis
          name: PHP-CS-Fixer
          php: 7.4
          env: dependencies=highest
          script: composer phpcs
        - <<: *code-style-static-analysis
          name: PHPStan
          script: composer phpstan
        - <<: *code-style-static-analysis
          name: Psalm
          script: composer psalm

install:
    - if [ "$TRAVIS_PHP_VERSION" = "nightly" ]; then composer remove --dev friendsofphp/php-cs-fixer --no-update --no-interaction; fi;
    - if [ "$dependencies" = "lowest" ]; then composer update --no-interaction --no-suggest --prefer-lowest --prefer-dist; fi;
    - if [ "$dependencies" = "highest" ]; then composer update --no-interaction --no-suggest --prefer-dist; fi;

script: >-
    vendor/bin/phpunit --coverage-clover=build/coverage-report.xml &&
    bash <(curl -s https://codecov.io/bash) -f build/coverage-report.xml

notifications:
    webhooks:
        urls:
            - https://zeus.ci/hooks/cf8597c4-ffba-11e7-89c9-0a580a281308/public/provider/travis/webhook
        on_success: always
        on_failure: always
        on_start: always
        on_cancel: always
        on_error: always
