language: php

branches:
  only:
  - master
  - /^release\/.+$/

php:
    - 7.1
    - 7.2
    - 7.3
    - nightly

env:
    - dependencies=highest
    - dependencies=lowest

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly

cache:
    directories:
        - $HOME/.composer/cache

stages:
    - Code style & static analysis
    - Test
    - Code coverage

jobs:
    include:
        - stage: Code style & static analysis
          name: PHP CS Fixer
          env: dependencies=highest
          script: composer phpcs
        - script: composer phpstan
          env: dependencies=highest
          name: PHPStan
        - stage: test
          name: HTTPlug 2
          install:
              - composer remove --dev php-http/curl-client --no-update --no-interaction
              - composer require php-http/httplug:^2.0 --no-update --no-interaction
              - composer require --dev php-http/guzzle6-adapter --no-update --no-interaction
              - composer update --no-interaction --no-suggest --prefer-dist
        - stage: Code coverage
          php: 7.3
          env: dependencies=highest
          script:
              - vendor/bin/phpunit --verbose --coverage-clover=build/logs/clover.xml
              - wget https://scrutinizer-ci.com/ocular.phar
              - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml --revision=$TRAVIS_COMMIT

install:
    - if [ "$dependencies" = "lowest" ]; then composer update --no-interaction --no-suggest --prefer-lowest --prefer-dist; fi;
    - if [ "$dependencies" = "highest" ]; then composer update --no-interaction --no-suggest --prefer-dist; fi;

notifications:
    webhooks:
        urls:
            - https://zeus.ci/hooks/cf8597c4-ffba-11e7-89c9-0a580a281308/public/provider/travis/webhook
        on_success: always
        on_failure: always
        on_start: always
        on_cancel: always
        on_error: always
