language: php

php:
    - 7.1
    - 7.2
    - 7.3
    - nightly

env:
    - dependencies=highest
    - dependencies=lowest

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly

cache:
    directories:
        - $HOME/.composer/cache

stages:
    - Code style & static analysis
    - Test
    - Code coverage

jobs:
    include:
        - stage: Code style & static analysis
          name: PHP CS Fixer
          env: dependencies=highest
          script: composer phpcs
        - script: composer phpstan
          env: dependencies=highest
          name: PHPStan
        - stage: Code coverage
          php: 7.3
          env: dependencies=highest
          script:
              - vendor/bin/phpunit --verbose --coverage-clover=build/logs/clover.xml
              - wget https://scrutinizer-ci.com/ocular.phar
              - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml --revision=$TRAVIS_COMMIT
          after_success:
              - travis_retry php vendor/bin/php-coveralls --verbose

install:
    - if [ "$dependencies" = "lowest" ]; then composer update --no-interaction --prefer-lowest --prefer-dist; fi;
    - if [ "$dependencies" = "highest" ]; then composer update --no-interaction --prefer-dist; fi;

notifications:
    webhooks:
        urls:
            - https://zeus.ci/hooks/cf8597c4-ffba-11e7-89c9-0a580a281308/public/provider/travis/webhook
        on_success: always
        on_failure: always
        on_start: always
        on_cancel: always
        on_error: always
